(()=>{
  'use strict';if(window.__FOOTBALL_LIFE_V10_LOCKER__)return;window.__FOOTBALL_LIFE_V10_LOCKER__=true;
  const V=window.V10;if(!V||!window.Game||!window.UI)return;V.ensureState();
  const roles=['주장','부주장','절친','포지션 경쟁자'];
  function ensure(){V.ensureState();const L=G.lockerV10,names=Object.keys(G.locker||{});while(names.length<4){const n=['민재','준호','태현','시후','현우'][names.length]||`동료${names.length+1}`;G.locker[n]=50;names.push(n)}
    names.forEach((n,i)=>{if(L.relations[n]==null)L.relations[n]=Number(G.locker[n])||50});if(!L.captain||L.captain==='주장')L.captain=names[0];if(!L.bestFriend)L.bestFriend=names.sort((a,b)=>L.relations[b]-L.relations[a])[0];if(!L.rival)L.rival=names.find(n=>n!==L.bestFriend)||names[1];if(!L.coachFavorite)L.coachFavorite=names[2]||names[0];return L}
  function sync(){const L=ensure();Object.entries(L.relations).forEach(([n,v])=>G.locker[n]=Math.round(v));G.teamChemistry=V.clamp(Object.values(L.relations).reduce((a,b)=>a+b,0)/Math.max(1,Object.keys(L.relations).length));}
  function log(s){const L=ensure();L.events.unshift(s);L.events=L.events.slice(0,12);V.addHistory(s)}
  Game.lockerAction=function(type,name=''){const L=ensure();if(type==='captain'){L.relations[L.captain]=V.clamp(L.relations[L.captain]+6);G.captainTrust=V.clamp((G.captainTrust||0)+8);log(`${L.captain} 주장과 따로 대화를 나눴다.`)}
    if(type==='friend'){const n=name||L.bestFriend;L.relations[n]=V.clamp(L.relations[n]+7);L.bestFriend=n;G.morale=V.clamp(G.morale+2);log(`${n}와 절친 관계가 깊어졌다.`)}
    if(type==='rival'){const n=name||L.rival;L.relations[n]=V.clamp(L.relations[n]-5);L.rival=n;L.tension=V.clamp(L.tension+7);G.form=V.clamp(G.form+2);log(`${n}와 포지션 경쟁이 과열됐다.`)}
    if(type==='neutral'){L.faction='중립';L.tension=V.clamp(L.tension-5);G.managerTrust=V.clamp(G.managerTrust+1);log('라커룸 파벌에 휘말리지 않고 중립을 지켰다.')}sync();V.safeSave();V.refresh();UI.show('manager')};

  function weekly(){const L=ensure();if(Math.random()<.12){L.newCoachCount++;const styles=['강한 압박','점유율','역습','수비 안정'];const s=styles[Math.floor(Math.random()*styles.length)];G.managerTrust=V.clamp(G.managerTrust-8);L.coachFavorite=Object.keys(L.relations)[Math.floor(Math.random()*Object.keys(L.relations).length)];log(`새 감독이 부임했다. 전술 성향은 '${s}'. 감독이 가장 먼저 주목한 선수는 ${L.coachFavorite}.`);G.inbox.push(['🧑‍💼 새 감독 부임',`새 감독이 ${s} 축구를 선언했다. 기존 주전 서열이 다시 시작된다.`,['전술에 맞춘다','내 장점을 강조','상황을 지켜본다']])}
    if(Math.random()<.22){const ns=Object.keys(L.relations),n=ns[Math.floor(Math.random()*ns.length)],good=Math.random()>.45;L.relations[n]=V.clamp(L.relations[n]+(good?4:-4));L.tension=V.clamp(L.tension+(good?-2:3));log(`${n}와 ${good?'훈련 호흡이 좋아졌다':'훈련 중 신경전이 있었다'}.`)}
    if(L.rival&&L.relations[L.rival]<30&&Math.random()<.25)G.inbox.push(['🔥 라커룸 라이벌 갈등',`${L.rival}이 언론에 주전 경쟁에 대한 불만을 드러냈다.`,['공개적으로 화해','경기력으로 답한다','무시한다']]);sync()}
  const oldAdv=Game.advanceWeek?.bind(Game);if(oldAdv)Game.advanceWeek=function(){const r=oldAdv(...arguments);weekly();V.safeSave();V.refresh();return r};

  const oldManager=UI.manager?.bind(UI);if(oldManager)UI.manager=function(){oldManager();const p=document.getElementById('page-manager');if(!p)return;const L=ensure();p.insertAdjacentHTML('beforeend',`<div class="grid" style="margin-top:10px"><div class="c12 panel pad"><div class="title"><h2>👥 라커룸 인간관계</h2><span class="pill">팀 케미 ${Math.round(G.teamChemistry)}</span></div><div class="lockerNetwork">${Object.entries(L.relations).map(([n,v])=>{const cls=n===L.captain?'captain':n===L.rival?'rival':n===L.bestFriend?'friend':'';const role=n===L.captain?'주장':n===L.rival?'포지션 라이벌':n===L.bestFriend?'절친':'동료';return `<div class="lockerPerson ${cls}"><div class="role">${role}</div><b>${n}</b><div class="rel">${Math.round(v)}</div><div class="bar"><i style="width:${v}%"></i></div><div class="btnrow" style="margin-top:8px"><button class="btn" onclick="Game.lockerAction('friend','${n.replace(/'/g,"\\'")}')">친해지기</button>${n!==L.captain?`<button class="btn red" onclick="Game.lockerAction('rival','${n.replace(/'/g,"\\'")}')">경쟁</button>`:''}</div></div>`}).join('')}</div><div class="btnrow" style="margin-top:10px"><button class="btn gold" onclick="Game.lockerAction('captain')">주장과 면담</button><button class="btn blue" onclick="Game.lockerAction('neutral')">파벌 중립 선언</button></div><div class="stat"><span>라커룸 긴장도</span><b>${Math.round(L.tension)}</b></div><div class="stat"><span>감독이 선호하는 선수</span><b>${L.coachFavorite}</b></div><div class="stat"><span>새 감독 부임 횟수</span><b>${L.newCoachCount}</b></div></div></div>`)};
  ensure();sync();V.safeSave();
})();
