(()=>{
  // FOOTBALL LIFE 9.5 runtime expansion
  const D=(obj,key,val)=>{if(obj[key]===undefined||obj[key]===null)obj[key]=val};
  G.saveVersion=9.5;
  D(G,'selectionStatus','선발 경쟁');D(G,'positionRank',4);D(G,'positionCompetitors',['김태윤','박시후','정민재','이도현'].map((n,i)=>({name:n,ovr:Math.max(45,G.ovr+2-i*2),form:55+i*3})));
  D(G,'injury',null);D(G,'injuryWeeks',0);D(G,'rehabProgress',0);D(G,'scoutReports',[]);D(G,'loanOffers',[]);D(G,'loanReturnClub',null);D(G,'loanWeeks',0);D(G,'transferHistory',[]);D(G,'clubStats',{});D(G,'continentalCompetition','리그 / 국내컵');D(G,'continentalHistory',[]);D(G,'worldCupTournament',null);D(G,'careerTrophies',[]);D(G,'squadOmissions',0);D(G,'benchApps',0);D(G,'starts',0);D(G,'managerDemandSuccess',0);D(G,'managerDemandMiss',0);
  const coachDemands=[
    {text:'라인 사이에서 공을 더 자주 받아!',focus:'pass',label:'킬패스/연결'},
    {text:'기회가 오면 과감하게 슈팅해!',focus:'shoot',label:'직접 슈팅'},
    {text:'상대 빌드업을 더 강하게 압박해!',focus:'press',label:'강한 압박'},
    {text:'지금은 볼을 잃지 말고 안전하게!',focus:'safe',label:'안전한 연결'},
    {text:'측면으로 운반해서 수비를 흔들어!',focus:'dribble',label:'드리블 돌파'}
  ];
  const css=document.createElement('style');css.textContent=`
    .nav button{position:relative}.navBadge{margin-left:auto;min-width:19px;height:19px;padding:0 5px;border-radius:999px;background:#ff3b30;color:#fff;font-size:11px;font-weight:1000;display:none;align-items:center;justify-content:center;box-shadow:0 0 0 2px #071722,0 4px 12px #ff3b3066}.navBadge.show{display:inline-flex}
    .coachDemand{margin-top:10px;border:1px solid #f1c75b;background:linear-gradient(135deg,#4a3810,#211c0d);border-radius:12px;padding:12px;box-shadow:0 10px 28px #0007}.coachDemand h3{margin:0 0 6px;color:#ffe592}.depthRow{display:grid;grid-template-columns:34px 1fr auto;gap:8px;align-items:center;padding:8px;border-bottom:1px solid #123649}.rankDot{width:28px;height:28px;border-radius:8px;background:#0d3447;display:grid;place-items:center;font-weight:900}.selection.start{color:#61f3b5}.selection.bench{color:#ffd36a}.selection.out{color:#ff7984}.scoutGrade{font-size:42px;font-weight:1000;color:#ffe18c}.rehabCard{border:1px solid #713842;background:#2b1218;border-radius:12px;padding:12px}.competitionTag{display:inline-flex;padding:5px 9px;border-radius:9px;background:#162f48;border:1px solid #286084;margin:3px;font-size:10px}.historyFee{color:#7bd3ff;font-weight:900}`;document.head.appendChild(css);
  const brand=document.querySelector('.brand span');if(brand)brand.textContent='9.5';
  const devBtn=document.querySelector('[data-page="development"]');if(devBtn&&!document.getElementById('badge-skill')){devBtn.innerHTML='<span>📈 선수 성장</span><span id="badge-skill" class="navBadge"></span>'}
  const inboxBtn=document.querySelector('[data-page="inbox"]');if(inboxBtn&&!document.getElementById('badge-inbox')){inboxBtn.innerHTML='<span>✉️ 인박스 / 라이브</span><span id="badge-inbox" class="navBadge"></span>'}
  function updateBadges(){const s=document.getElementById('badge-skill');if(s){s.textContent=G.skillPoints;s.classList.toggle('show',G.skillPoints>0)}const i=document.getElementById('badge-inbox');if(i){i.textContent=G.inbox.length>9?'9+':G.inbox.length;i.classList.toggle('show',G.inbox.length>0)}}
  const oldTop=UI.renderTop.bind(UI);UI.renderTop=function(){oldTop();updateBadges()};
  const oldAll=UI.renderAll.bind(UI);UI.renderAll=function(){oldAll();updateBadges()};
  const oldGain=Game.gainXP.bind(Game);Game.gainXP=function(n){oldGain(n);updateBadges()};
  const oldSpend=Game.spendSkill.bind(Game);Game.spendSkill=function(a){oldSpend(a);updateBadges()};
  const grade=()=>{const s=G.ovr*.45+G.potential*.35+G.form*.2;return s>=80?'A+':s>=74?'A':s>=68?'B+':s>=62?'B':s>=56?'C+':'C'};
  Game.updateSelection=function(){if(G.injuryWeeks>0){G.selectionStatus='명단 제외';return}const score=G.ovr+G.form/5+G.managerTrust/10+(G.stage==='youth'?G.academyRep/20:0);const rivals=G.positionCompetitors.map(p=>p.ovr+p.form/5);G.positionRank=1+rivals.filter(x=>x>score).length;G.selectionStatus=G.positionRank<=1&&G.managerTrust>=52?'선발':G.positionRank<=3&&G.managerTrust>=38?'벤치':'명단 제외'};
  Game.generateScoutReport=function(show=true){const sorted=Object.entries(G.attrs).sort((a,b)=>b[1]-a[1]);const r={year:G.year,age:G.age,grade:grade(),text:`강점 ${skillNames[sorted[0][0]]}·${skillNames[sorted[1][0]]}, 보완 ${skillNames[sorted.at(-1)[0]]}. ${G.pos} 포지션 경쟁 ${G.positionRank}순위. 잠재력 ${G.potential}.`};G.scoutReports.unshift(r);G.scoutReports=G.scoutReports.slice(0,8);save();if(show){UI.show('development');UI.toast('새 스카우트 평가서가 도착했습니다.')}};
  if(!G.scoutReports.length)Game.generateScoutReport(false);
  Game.rehab=function(type){if(G.injuryWeeks<=0)return UI.toast('현재 부상이 없습니다.');if(type==='rest'){G.rehabProgress=clamp(G.rehabProgress+18);G.fitness=clamp(G.fitness+8);G.injuryRisk=clamp(G.injuryRisk-8)}if(type==='physio'){const cost=G.stage==='youth'?0:1200000;if(G.money<cost)return UI.toast('비용이 부족합니다.');G.money-=cost;G.rehabProgress=clamp(G.rehabProgress+30);G.injuryWeeks=Math.max(0,G.injuryWeeks-1)}if(type==='rush'){G.rehabProgress=clamp(G.rehabProgress+35);G.injuryWeeks=Math.max(0,G.injuryWeeks-2);G.injuryRisk=clamp(G.injuryRisk+20)}if(G.rehabProgress>=100||G.injuryWeeks<=0){G.injury=null;G.injuryWeeks=0;G.rehabProgress=0;G.history.unshift('재활을 마치고 팀 훈련에 복귀했다.')}save();UI.renderAll()};
  Game.createInjury=function(source='경기'){const p=[['발목 염좌',2],['햄스트링',3],['무릎 타박',2],['허벅지 근육',4]][Math.floor(Math.random()*4)];G.injury={name:p[0],source};G.injuryWeeks=p[1];G.rehabProgress=0;G.fitness=clamp(G.fitness-18);G.history.unshift(`${source} 중 ${p[0]} 부상 · ${p[1]}주 예상.`)};
  Game.generateLoanOffers=function(show=true){if(G.stage==='youth'||G.age>23){G.loanOffers=[];return}const c=['부산 아이파크','김포 FC','수원 삼성','FC 안양','PEC Zwolle','Sparta Rotterdam'].sort(()=>Math.random()-.5).slice(0,2);G.loanOffers=c.map(club=>({club,weeks:26,role:'주전 경쟁'}));save();if(show)UI.show('transfer')};
  Game.acceptLoan=function(i){const o=G.loanOffers[i];if(!o)return;const from=G.club;G.loanReturnClub=from;G.club=o.club;G.loanWeeks=o.weeks;G.managerTrust=52;G.role='임대 · 주전 경쟁';G.transferHistory.unshift({year:G.year,type:'임대',from,to:o.club,fee:'임대'});G.loanOffers=[];save();UI.renderAll();UI.toast(`${o.club} 임대 완료`)};
  const oldAccept=Game.acceptOffer.bind(Game);Game.acceptOffer=function(i){const o=G.transferOffers[i];if(!o)return;const from=G.club,fee=o.fee;oldAccept(i);G.transferHistory.unshift({year:G.year,type:'완전이적',from,to:G.club,fee});G.continentalCompetition=/Real Madrid|Barcelona|Manchester City|Liverpool|Arsenal|Bayern|PSG|Inter/.test(G.club)?'UEFA Champions League':/PSV|Ajax|Feyenoord|Tottenham|Dortmund|Leverkusen|Milan|Napoli|Marseille|Monaco/.test(G.club)?'UEFA Europa League':'AFC Champions League Elite';save()};
  const oldDev=UI.development.bind(UI);UI.development=function(){oldDev();const p=document.querySelector('#page-development');const r=G.scoutReports[0];p.insertAdjacentHTML('beforeend',`<div class="grid" style="margin-top:10px"><div class="c6 panel pad"><div class="title"><h2>스카우트 평가서</h2><button class="btn blue" onclick="Game.generateScoutReport(true)">새 평가</button></div><div class="scoutGrade">${r?.grade||grade()}</div><p>${r?.text||''}</p><div class="stat"><span>포지션 순위</span><b>${G.positionRank}</b></div></div><div class="c6 panel pad"><div class="title"><h2>부상 / 재활</h2></div>${G.injuryWeeks>0?`<div class="rehabCard"><b>${G.injury.name}</b><p>${G.injuryWeeks}주 · 재활 ${G.rehabProgress}%</p><div class="btnrow"><button class="btn green" onclick="Game.rehab('rest')">안정 재활</button><button class="btn blue" onclick="Game.rehab('physio')">피지오</button><button class="btn red" onclick="Game.rehab('rush')">빠른 복귀</button></div></div>`:`<div class="notice">현재 부상 없음 · 부상 위험 ${G.injuryRisk}%</div>`}</div></div>`);updateBadges()};
  const oldMgr=UI.manager.bind(UI);UI.manager=function(){oldMgr();const p=document.querySelector('#page-manager');const panel=p.querySelector('.grid');if(panel)panel.insertAdjacentHTML('afterbegin',`<div class="c12 panel pad"><div class="title"><h2>포지션 경쟁 / 명단 상태</h2><span class="pill">${G.selectionStatus}</span></div><div class="depthRow"><div class="rankDot">${G.positionRank}</div><div><b>${G.name}</b><small class="muted"> · OVR ${G.ovr} · 폼 ${G.form}</small></div><b>${G.selectionStatus}</b></div>${G.positionCompetitors.map((x,i)=>`<div class="depthRow"><div class="rankDot">${i+1}</div><div><b>${x.name}</b><small class="muted"> · OVR ${x.ovr} · 폼 ${x.form}</small></div><span>경쟁</span></div>`).join('')}<div class="stat"><span>감독 지시 성공 / 실패</span><b>${G.managerDemandSuccess} / ${G.managerDemandMiss}</b></div></div>`)};
  const oldTransfer=UI.transfer.bind(UI);UI.transfer=function(){oldTransfer();if(G.stage==='youth')return;const p=document.querySelector('#page-transfer');p.insertAdjacentHTML('beforeend',`<div class="grid" style="margin-top:10px"><div class="c5 panel pad"><div class="title"><h2>임대 시장</h2><button class="btn" onclick="Game.generateLoanOffers(true)">제안 확인</button></div>${G.loanOffers.map((o,i)=>`<div class="card"><strong>${o.club}</strong><p>${o.weeks}주 임대 · ${o.role}</p><button class="btn gold" onclick="Game.acceptLoan(${i})">임대 수락</button></div>`).join('')||'<div class="notice">현재 임대 제안 없음</div>'}</div><div class="c7 panel pad"><div class="title"><h2>이적료 / 커리어 이동 기록</h2></div>${G.transferHistory.map(h=>`<div class="stat"><span>${h.year} · ${h.type} · ${h.from} → ${h.to}</span><b class="historyFee">${h.fee}</b></div>`).join('')||'<div class="notice">아직 공식 이동 기록 없음</div>'}</div></div>`)};
  Game.answerCoachDemand=function(choice){const m=G.matchSession;if(!m||!m.managerDemand)return;const d=m.managerDemand;if(choice==='obey'){m.coachFocus=d.focus;m.coachFocusTurns=2;G.managerTrust=clamp(G.managerTrust+1);m.log.push(`${m.minute}' 감독 지시를 따르겠다고 응답.`)}else if(choice==='adapt'){m.coachFocus=d.focus;m.coachFocusTurns=1;m.rating+=.05}else{m.coachFocus=null;m.coachFocusTurns=0;G.managerTrust=clamp(G.managerTrust-2);G.managerDemandMiss++;m.log.push(`${m.minute}' 감독 지시보다 자신의 판단을 선택.`)}m.managerDemand=null;save();UI.show('match')};
  const oldStart=Game.startMatch.bind(Game);Game.startMatch=function(){if(G.injuryWeeks>0)return UI.toast('부상 재활을 먼저 마쳐야 합니다.');Game.updateSelection();if(G.selectionStatus==='명단 제외'){G.squadOmissions++;const f=G.fixtures.shift();if(f)G.history.unshift(`${f[1]} ${f[0]}전 명단 제외.`);save();UI.renderAll();return UI.toast('이번 경기 명단에서 제외됐습니다.')}oldStart();if(G.matchSession){const m=G.matchSession;m.starter=G.selectionStatus==='선발';m.actionsTaken=0;m.managerDemand=null;m.demandCount=0;m.demandSuccess=0;m.coachFocus=null;m.coachFocusTurns=0;if(m.starter)G.starts++;else{G.benchApps++;m.half=2;m.minute=58;m.left=4;m.halftimeDone=true;m.log=["58' 🔄 벤치에서 교체 투입됐다."]}save();UI.show('match')}};
  const oldAction=Game.matchAction.bind(Game);Game.matchAction=function(type){const m=G.matchSession;if(!m||m.managerDemand)return;if(m.coachFocus===type){m.rating+=.1;m.demandSuccess++;G.managerDemandSuccess++;G.managerTrust=clamp(G.managerTrust+1)}else if(m.coachFocus&&m.coachFocusTurns>0){G.managerDemandMiss++;m.rating-=.05}if(m.coachFocusTurns>0){m.coachFocusTurns--;if(!m.coachFocusTurns)m.coachFocus=null}oldAction(type);if(!G.matchSession)return;const n=G.matchSession;n.actionsTaken=(n.actionsTaken||0)+1;if([2,4,6].includes(n.actionsTaken)&&(n.demandCount||0)<3&&!n.managerDemand){const d=coachDemands[Math.floor(Math.random()*coachDemands.length)];n.managerDemand={...d};n.demandCount=(n.demandCount||0)+1;n.log.push(`${n.minute}' 🎙️ 감독 지시: “${d.text}”`)}if(['press','dribble','hero'].includes(type)&&Math.random()<G.injuryRisk/900){Game.createInjury('경기');n.subbed=true;n.log.push(`${n.minute}' 🩹 부상으로 교체됐다.`)}save();UI.show('match')};
  const oldMatchUI=UI.match.bind(UI);UI.match=function(){oldMatchUI();const m=G.matchSession;if(m?.managerDemand){const main=document.querySelector('#page-match .c8.panel.pad');if(main){const node=document.createElement('div');node.className='coachDemand';node.innerHTML=`<h3>🎙️ 감독의 터치라인 지시</h3><b>“${m.managerDemand.text}”</b><p class="muted">요구 플레이: ${m.managerDemand.label}</p><div class="btnrow"><button class="btn green" onclick="Game.answerCoachDemand('obey')">따르겠습니다</button><button class="btn blue" onclick="Game.answerCoachDemand('adapt')">상황에 맞게</button><button class="btn red" onclick="Game.answerCoachDemand('ignore')">내 판단대로</button></div>`;main.prepend(node)}}};
  Game.startContinentalMatch=function(){if(G.stage==='youth')return UI.toast('프로 이후 개방됩니다.');if(G.matchSession)return UI.show('match');const comp=G.continentalCompetition||'UEFA Europa League';const opp=comp.includes('Champions')?'Bayern München':comp.includes('Europa')?'Roma':'Al Hilal';G.matchSession={opp,comp,continental:true,half:1,minute:1,us:0,them:0,left:8,rating:6.4,energy:G.fitness,goals:0,assists:0,shots:0,keyPasses:0,yellow:0,red:false,subbed:false,tactic:'균형',halftimeDone:false,starter:true,actionsTaken:0,managerDemand:null,demandCount:0,demandSuccess:0,coachFocus:null,coachFocusTurns:0,log:[`1' 🌍 ${comp}: ${G.club} vs ${opp}`]};UI.show('match');save()};
  Game.startWorldCupTournament=function(){if(G.stage==='youth'||G.nationalRep<70)return UI.toast('대표팀 평가가 부족합니다.');G.worldCupTournament={stage:'조별리그',opponents:['포르투갈','우루과이','가나'],index:0,points:0,active:true};G.worldCupPlayedYear=G.year;save();UI.show('national')};
  Game.startWorldCupMatch=function(){const t=G.worldCupTournament;if(!t?.active)return UI.toast('진행 중인 월드컵이 없습니다.');if(G.matchSession)return UI.show('match');const opp=t.opponents[t.index];G.matchSession={opp,comp:`월드컵 ${t.stage}`,international:true,half:1,minute:1,us:0,them:0,left:8,rating:6.5,energy:G.fitness,goals:0,assists:0,shots:0,keyPasses:0,yellow:0,red:false,subbed:false,tactic:'균형',halftimeDone:false,starter:true,actionsTaken:0,managerDemand:null,demandCount:0,demandSuccess:0,coachFocus:null,coachFocusTurns:0,log:[`1' 🌍 월드컵 ${t.stage}: 대한민국 vs ${opp}`]};save();UI.show('match')};
  const oldFinish=Game.finishMatch.bind(Game);Game.finishMatch=function(){const m=G.matchSession;if(!m)return;if(m.international||m.continental){const result=m.us>m.them?'승':m.us<m.them?'패':'무';if(m.international){G.nationalCaps++;G.nationalGoals+=m.goals;G.worldCupApps++;G.worldCupGoals+=m.goals;const t=G.worldCupTournament;t.points+=result==='승'?3:result==='무'?1:0;t.index++;if(t.stage==='조별리그'&&t.index>=3){if(t.points>=4){t.stage='16강';t.opponents.push('스페인');G.worldCupBest='16강'}else{t.active=false;G.worldCupBest='조별리그'}}else if(t.stage!=='조별리그'){const stages=['16강','8강','4강','결승'];if(result==='패'){t.active=false;G.worldCupBest=t.stage}else{const i=stages.indexOf(t.stage);if(i===3){t.active=false;G.worldCupBest='우승';G.careerTrophies.push(`${G.year} 월드컵 우승`)}else{t.stage=stages[i+1];t.opponents.push(['프랑스','브라질','아르헨티나'][Math.min(i,2)]);G.worldCupBest=t.stage}}}}else{G.continentalHistory.unshift(`${G.year} ${m.comp}: ${m.us}-${m.them} ${result} vs ${m.opp}`)}G.fitness=clamp(m.energy);G.history.unshift(`${m.comp} ${m.opp}전 ${m.us}-${m.them} ${result} · 평점 ${m.rating.toFixed(1)}`);Game.gainXP(Math.round(30+m.rating*4+m.goals*18+m.assists*12));G.matchSession=null;save();UI.renderAll();return UI.toast('특별 대회 경기가 종료됐습니다.')}const club=G.club;const g=m.goals,a=m.assists;oldFinish();const st=G.clubStats[club]||(G.clubStats[club]={apps:0,goals:0,assists:0});st.apps++;st.goals+=g;st.assists+=a;save()};
  const oldStand=UI.standings.bind(UI);UI.standings=function(){oldStand();const p=document.querySelector('#page-standings');p.insertAdjacentHTML('beforeend',`<div class="grid" style="margin-top:10px"><div class="c6 panel pad"><div class="title"><h2>대륙대항전</h2><span class="pill">${G.continentalCompetition}</span></div><p class="muted">유럽 진출 후 구단 수준에 따라 챔피언스리그/유로파가 열린다.</p>${G.stage!=='youth'?'<button class="btn gold" onclick="Game.startContinentalMatch()">대륙대항전 경기 직접 플레이</button>':''}</div><div class="c6 panel pad"><div class="title"><h2>트로피 / 유럽 기록</h2></div>${G.careerTrophies.map(x=>`<div class="stat"><span>🏆 ${x}</span></div>`).join('')||'<div class="notice">아직 주요 트로피 없음</div>'}${G.continentalHistory.slice(0,4).map(x=>`<div class="stat"><span>${x}</span></div>`).join('')}</div></div>`)};
  const oldNat=UI.national.bind(UI);UI.national=function(){oldNat();if(G.stage==='youth')return;const p=document.querySelector('#page-national');const t=G.worldCupTournament;p.insertAdjacentHTML('beforeend',`<div class="panel pad" style="margin-top:10px"><div class="title"><h2>🌍 월드컵 직접 플레이</h2><span class="pill">${t?.stage||'대기'}</span></div>${t?.active?`<div class="notice">${t.stage} · 승점 ${t.points} · ${t.index}/${t.opponents.length}경기</div><button class="btn green" onclick="Game.startWorldCupMatch()">다음 월드컵 경기 직접 플레이</button>`:`<button class="btn gold" onclick="Game.startWorldCupTournament()">월드컵 본선 시작</button>`}</div>`)};
  const oldWeek=Game.advanceWeek.bind(Game);Game.advanceWeek=function(){const wasMatch=!!G.matchSession;oldWeek();if(wasMatch||G.matchSession)return;if(G.loanWeeks>0){G.loanWeeks--;if(G.loanWeeks===0&&G.loanReturnClub){const from=G.club;G.club=G.loanReturnClub;G.loanReturnClub=null;G.history.unshift(`${from} 임대 종료 · 원소속팀 복귀`)}}if(G.injuryWeeks>0){G.injuryWeeks--;G.rehabProgress=clamp(G.rehabProgress+15);if(G.injuryWeeks<=0){G.injury=null;G.injuryWeeks=0;G.rehabProgress=0}}if(G.week%4===0){Game.generateScoutReport(false);if(G.stage!=='youth'&&G.age<=22)Game.generateLoanOffers(false)}Game.updateSelection();save();UI.renderAll()};
  Game.updateSelection();save();UI.renderAll();
})();
